version: '3'

services:
  zip2xml:
    image: dubmn/zap2xml:latest
    restart: always
    volumes:
        - /xmltvdata:/data
    environment:
        - USERNAME=myemail@email.com
        - PASSWORD=**password**
        - OPT_ARGS=-I -D
        - USERNAME2=myemail2@email.com #Optional
        - PASSWORD2=**secondpassword** #Optional
        - OPT_ARGS2=-I -D #Optional
        - XMLTV_FILENAME=zip2xml.xml
