version: '3'

services:
  zap2xml:
    image: dubmn/zap2xml:latest
    container_name: zap2xml
    volumes:
        - /path/to/xmltvdata:/data #Map from local path
    environment:
        - USERNAME=myemail@email.com
        - PASSWORD=**password**
        - OPT_ARGS=-I -D
        - USERNAME2=myemail2@email.com #Optional
        - PASSWORD2=**secondpassword** #Optional
        - OPT_ARGS2=-I -D #Optional
        - XMLTV_FILENAME=zip2xmltv.xml #Optional
    restart: always
